### ISSUE TITLE
w2v_description_cub.mat file formed from the CUB_description.xlsx file？

### ISSUE THREAD

**Issue by WenshangY** [FHShubho/CGS-ZSL#1]
Hello!
Thank you very much for the partial code, is the w2v_description_cub.mat file formed from the CUB_description.xlsx file based on the splits standard of att_splits.mat in xlsa17?
The att_splits.mat file should have been generated from the original 312-dimensional attributes. Can you provide the original code that formed the att_splits.mat file or a link to it?

**Comment by FHShubho** [comment]
The original att_splits.mat file provided by the authors is available at https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly
